/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Scheme } from "./Scheme";
import { SchemeCountArgs } from "./SchemeCountArgs";
import { SchemeFindManyArgs } from "./SchemeFindManyArgs";
import { SchemeFindUniqueArgs } from "./SchemeFindUniqueArgs";
import { CreateSchemeArgs } from "./CreateSchemeArgs";
import { UpdateSchemeArgs } from "./UpdateSchemeArgs";
import { DeleteSchemeArgs } from "./DeleteSchemeArgs";
import { StageFindManyArgs } from "../../stage/base/StageFindManyArgs";
import { Stage } from "../../stage/base/Stage";
import { DynamicFieldFindManyArgs } from "../../dynamicField/base/DynamicFieldFindManyArgs";
import { DynamicField } from "../../dynamicField/base/DynamicField";
import { ApplicationFindManyArgs } from "../../application/base/ApplicationFindManyArgs";
import { Application } from "../../application/base/Application";
import { SchemeService } from "../scheme.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Scheme)
export class SchemeResolverBase {
  constructor(
    protected readonly service: SchemeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Scheme",
    action: "read",
    possession: "any",
  })
  async _schemesMeta(
    @graphql.Args() args: SchemeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Scheme])
  @nestAccessControl.UseRoles({
    resource: "Scheme",
    action: "read",
    possession: "any",
  })
  async schemes(@graphql.Args() args: SchemeFindManyArgs): Promise<Scheme[]> {
    return this.service.schemes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Scheme, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Scheme",
    action: "read",
    possession: "own",
  })
  async scheme(
    @graphql.Args() args: SchemeFindUniqueArgs
  ): Promise<Scheme | null> {
    const result = await this.service.scheme(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Scheme)
  @nestAccessControl.UseRoles({
    resource: "Scheme",
    action: "create",
    possession: "any",
  })
  async createScheme(@graphql.Args() args: CreateSchemeArgs): Promise<Scheme> {
    return await this.service.createScheme({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Scheme)
  @nestAccessControl.UseRoles({
    resource: "Scheme",
    action: "update",
    possession: "any",
  })
  async updateScheme(
    @graphql.Args() args: UpdateSchemeArgs
  ): Promise<Scheme | null> {
    try {
      return await this.service.updateScheme({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Scheme)
  @nestAccessControl.UseRoles({
    resource: "Scheme",
    action: "delete",
    possession: "any",
  })
  async deleteScheme(
    @graphql.Args() args: DeleteSchemeArgs
  ): Promise<Scheme | null> {
    try {
      return await this.service.deleteScheme(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Stage], { name: "stages" })
  @nestAccessControl.UseRoles({
    resource: "Stage",
    action: "read",
    possession: "any",
  })
  async findStages(
    @graphql.Parent() parent: Scheme,
    @graphql.Args() args: StageFindManyArgs
  ): Promise<Stage[]> {
    const results = await this.service.findStages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [DynamicField], { name: "dynamicFields" })
  @nestAccessControl.UseRoles({
    resource: "DynamicField",
    action: "read",
    possession: "any",
  })
  async findDynamicFields(
    @graphql.Parent() parent: Scheme,
    @graphql.Args() args: DynamicFieldFindManyArgs
  ): Promise<DynamicField[]> {
    const results = await this.service.findDynamicFields(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Application], { name: "applications" })
  @nestAccessControl.UseRoles({
    resource: "Application",
    action: "read",
    possession: "any",
  })
  async findApplications(
    @graphql.Parent() parent: Scheme,
    @graphql.Args() args: ApplicationFindManyArgs
  ): Promise<Application[]> {
    const results = await this.service.findApplications(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
