/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DynamicFieldService } from "../dynamicField.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DynamicFieldCreateInput } from "./DynamicFieldCreateInput";
import { DynamicField } from "./DynamicField";
import { DynamicFieldFindManyArgs } from "./DynamicFieldFindManyArgs";
import { DynamicFieldWhereUniqueInput } from "./DynamicFieldWhereUniqueInput";
import { DynamicFieldUpdateInput } from "./DynamicFieldUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DynamicFieldControllerBase {
  constructor(
    protected readonly service: DynamicFieldService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DynamicField })
  @nestAccessControl.UseRoles({
    resource: "DynamicField",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDynamicField(
    @common.Body() data: DynamicFieldCreateInput
  ): Promise<DynamicField> {
    return await this.service.createDynamicField({
      data: {
        ...data,

        stage: data.stage
          ? {
              connect: data.stage,
            }
          : undefined,

        scheme: data.scheme
          ? {
              connect: data.scheme,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        value: true,

        stage: {
          select: {
            id: true,
          },
        },

        scheme: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DynamicField] })
  @ApiNestedQuery(DynamicFieldFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DynamicField",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dynamicFields(@common.Req() request: Request): Promise<DynamicField[]> {
    const args = plainToClass(DynamicFieldFindManyArgs, request.query);
    return this.service.dynamicFields({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        value: true,

        stage: {
          select: {
            id: true,
          },
        },

        scheme: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DynamicField })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DynamicField",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dynamicField(
    @common.Param() params: DynamicFieldWhereUniqueInput
  ): Promise<DynamicField | null> {
    const result = await this.service.dynamicField({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        value: true,

        stage: {
          select: {
            id: true,
          },
        },

        scheme: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DynamicField })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DynamicField",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDynamicField(
    @common.Param() params: DynamicFieldWhereUniqueInput,
    @common.Body() data: DynamicFieldUpdateInput
  ): Promise<DynamicField | null> {
    try {
      return await this.service.updateDynamicField({
        where: params,
        data: {
          ...data,

          stage: data.stage
            ? {
                connect: data.stage,
              }
            : undefined,

          scheme: data.scheme
            ? {
                connect: data.scheme,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          value: true,

          stage: {
            select: {
              id: true,
            },
          },

          scheme: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DynamicField })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DynamicField",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDynamicField(
    @common.Param() params: DynamicFieldWhereUniqueInput
  ): Promise<DynamicField | null> {
    try {
      return await this.service.deleteDynamicField({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          value: true,

          stage: {
            select: {
              id: true,
            },
          },

          scheme: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
